LOAD DATA
INFILE *
INTO TABLE DEPT
REPLACE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
( DEPTNO,
  FILLER_1 FILLER,
  DNAME,
  LOC
)
BEGINDATA
20,Something Not To Be Loaded,Accounting,"Virginia,USA"
