CPU=i386

MSDEV       = c:\msdev
ORACLE_HOME = c:\oracle

!include <$(MSDEV)\include\win32.mak>

TGTDLL  = extproc.dll
OBJS    = extproc.obj

NTUSER32LIBS    = $(MSDEV)\lib\user32.lib   \
				  $(MSDEV)\lib\msvcrt.lib  \
				  $(MSDEV)\lib\oldnames.lib  \
				  $(MSDEV)\lib\kernel32.lib   \
				  $(MSDEV)\lib\advapi32.lib  

SQLLIB  =  $(ORACLE_HOME)\precomp\lib\msvc\orasql8.lib  \
           $(ORACLE_HOME)\oci\lib\msvc\oci.lib

INCLS   = -I$(MSDEV)\include \
		  -I$(ORACLE_HOME)\oci\include \
		  -I.

CFLAGS  = $(INCLS) -DWIN32 -DWIN_NT -D_DLL

all: $(TGTDLL) 

clean:
	erase *.obj *.lib *.exp 

$(TGTDLL): $(OBJS) 
    $(link) -DLL $(dllflags) \
		/NODEFAULTLIB:LIBC.LIB -out:$(TGTDLL) \
		$(OBJS) \
        $(NTUSER32LIBS) \
		$(SQLLIB)
