DROP TABLE UNIVERSITY;
DROP TABLE CITY;
DROP TABLE REGION;
DROP TABLE COUNTRY;
DROP SEQUENCE COUNTRY_SEQ;
DROP SEQUENCE REGION_SEQ;
DROP SEQUENCE CITY_SEQ;
DROP SEQUENCE UNIVERSITY_SEQ;

CREATE TABLE COUNTRY (
	ID NUMBER NOT NULL,
	NAME VARCHAR2(256) NOT NULL UNIQUE,
	LANG VARCHAR2(256), 
	CAPITAL VARCHAR(256),
	POPULATION NUMBER,
	TIMEZONE NUMBER, 
	CONSTRAINT COUNTRY_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE COUNTRY_SEQ
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 350
	MINVALUE 1
	CACHE 5;

CREATE TABLE REGION (
	PARENT_ID NUMBER NOT NULL, 
	ID NUMBER NOT NULL,
	NAME VARCHAR2(256) NOT NULL, 
	POPULATION NUMBER, 
	SQUARE NUMBER, 
	CONSTRAINT REGION_PK PRIMARY KEY (ID), 
	CONSTRAINT REGION_FK FOREIGN KEY (PARENT_ID) REFERENCES  COUNTRY (ID) ON DELETE CASCADE
);

CREATE SEQUENCE REGION_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	CACHE 5;

CREATE TABLE CITY (
	PARENT_ID NUMBER NOT NULL, 
	ID NUMBER NOT NULL, 
	NAME VARCHAR2(256) NOT NULL, 
	POPULATION NUMBER, 
	SQUARE NUMBER, 
	CONSTRAINT CITY_PK PRIMARY KEY (ID), 
	CONSTRAINT CITY_FK FOREIGN KEY (PARENT_ID) REFERENCES  REGION (ID) ON DELETE CASCADE
);

CREATE SEQUENCE CITY_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	CACHE 5;

CREATE TABLE UNIVERSITY (
	PARENT_ID NUMBER NOT NULL, 
	ID NUMBER NOT NULL, 
	NAME VARCHAR2(256) NOT NULL,
	DEPTS_COUNT NUMBER, 
	WWW VARCHAR2(256), 
	CONSTRAINT UNIVERSITY_PK PRIMARY KEY (ID), 
	CONSTRAINT UNIVERSITY_FK FOREIGN KEY (PARENT_ID) REFERENCES  CITY (ID) ON DELETE CASCADE
);

CREATE SEQUENCE UNIVERSITY_SEQ
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	CACHE 5;

commit;