ALTER TABLE COUNTRY DISABLE PRIMARY KEY;
ALTER TABLE REGION DISABLE PRIMARY KEY;
ALTER TABLE CITY DISABLE PRIMARY KEY;
ALTER TABLE UNIVERSITY DISABLE PRIMARY KEY;

ALTER TABLE REGION DISABLE CONSTRAINT REGION_FK;
ALTER TABLE CITY DISABLE CONSTRAINT CITY_FK;
ALTER TABLE UNIVERSITY DISABLE CONSTRAINT UNIVERSITY_FK;


TRUNCATE TABLE COUNTRY;
TRUNCATE TABLE REGION;
TRUNCATE TABLE CITY;
TRUNCATE TABLE UNIVERSITY;


ALTER TABLE COUNTRY ENABLE PRIMARY KEY;
ALTER TABLE REGION ENABLE PRIMARY KEY;
ALTER TABLE CITY ENABLE PRIMARY KEY;
ALTER TABLE UNIVERSITY ENABLE PRIMARY KEY;

ALTER TABLE REGION ENABLE CONSTRAINT REGION_FK;
ALTER TABLE CITY ENABLE CONSTRAINT CITY_FK;
ALTER TABLE UNIVERSITY ENABLE CONSTRAINT UNIVERSITY_FK;

INSERT INTO COUNTRY VALUES (COUNTRY_SEQ.NEXTVAL, 'USA', 'English (US)', 'Washington', 317320000, null);
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Alabama', null, null);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'Mobile', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Spring Hill College', null, 'http://www.shc.edu/');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'Troy', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Troy State University', null, 'http://www.troyst.edu/');
			
			
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Arizona', null, null);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'Prescott', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Embry-Riddle Aero. Univ.', null, 'http://www.embryriddle.edu/');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'Flagstaff', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Northern Arizona University', null, 'http://www.nau.edu/');
			
			
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'California', null, null);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'Claremont', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Claremont McKenna Coll.', null, 'http://www.mckenna.edu/');
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Harvey Mudd College ', null, 'http://www.hmc.edu/');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'San Francisco', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Golden Gate University', null, 'http://www.ggu.edu/');
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'University of San Francisco', null, 'http://www.usfca.edu/');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'Malibu', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Pepperdine University', null, 'http://www.pepperdine.edu/');
			
			
			
INSERT INTO COUNTRY VALUES (COUNTRY_SEQ.NEXTVAL, 'Ukraine', 'Ukrainian', 'Kyiv', 45447010, 2);
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Sumy region', 1137069, 23834000);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'Sumy', 271016, 145);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Sumy State Makarenko Pedagogical University', 8, 'www.sspu.sumy.ua');
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Sumy National Agrarian University', 9, 'www.sau.sumy.ua');
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Ukrainian Academy of Banking', 3, 'www.uabs.edu.ua');
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Sumy Institute of Inter-Regional Academy of Personnel Management', 3, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Sumy State University', 5, 'www.sumdu.edu.ua');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'Shostka', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Shostka Institute of Sumy State University', null, 'http://shinst.sumdu.edu.ua/');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'Konotop', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Konotop Institute of Sumy State University', null, 'http://kisumdu.konotop.org/');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'Hlukhiv', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Hluhkhiv Dovzhenko Pedagogical University', null, null);
			
			
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Kiev region', 1722875, 28131000);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 1', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'University 1', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 2', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 2', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 3', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 3', null, null);
	
	
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Kharkov region', 2762200, 31415000);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 1', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'University 1', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 2', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 2', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 3', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 3', null, null);
	
	
	
INSERT INTO COUNTRY VALUES (COUNTRY_SEQ.NEXTVAL, 'Russia', 'Russian', 'Moscow', 143608700, null);
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Region 1', 2762200, 31415000);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 1', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'University 1', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 2', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 2', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 3', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 3', null, null);
			
			
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Region 2', 2762200, 31415000);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 1', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'University 1', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 2', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 2', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 3', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 3', null, null);
			
			
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Region 3', 2762200, 31415000);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 1', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'University 1', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 2', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 2', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 3', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 3', null, null);
	
	
	
INSERT INTO COUNTRY VALUES (COUNTRY_SEQ.NEXTVAL, 'United Kingdom', 'English (UK)', 'London', 63887988, null);
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Region 1', 2762200, 31415000);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 1', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'University 1', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 2', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 2', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 3', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 3', null, null);
			
			
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Region 2', 2762200, 31415000);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 1', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'University 1', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 2', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 2', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 3', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 3', null, null);
			
			
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Region 3', 2762200, 31415000);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 1', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'University 1', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 2', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 2', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 3', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 3', null, null);
	
	
	
INSERT INTO COUNTRY VALUES (COUNTRY_SEQ.NEXTVAL, 'Japan', 'Japanese', 'Tokyo', 127325000, 9);
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Region 1', 2762200, 31415000);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 1', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'University 1', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 2', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 2', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 3', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 3', null, null);
			
			
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Region 2', 2762200, 31415000);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 1', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'University 1', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 2', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 2', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 3', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 3', null, null);
			
			
	INSERT INTO REGION VALUES (COUNTRY_SEQ.CURRVAL, REGION_SEQ.NEXTVAL, 'Region 3', 2762200, 31415000);
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 1', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'University 1', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 2', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 2', null, 'http://');
			
		INSERT INTO CITY VALUES (REGION_SEQ.CURRVAL, CITY_SEQ.NEXTVAL, 'City 3', null, null);
			INSERT INTO UNIVERSITY VALUES (CITY_SEQ.CURRVAL, UNIVERSITY_SEQ.NEXTVAL, 'Uni 3', null, null);
			

commit;
