set echo on

drop table dept_and_emp;

CREATE TABLE "TKYTE"."DEPT_AND_EMP"
("DEPTNO" NUMBER(2, 0),
 "DNAME"  VARCHAR2(14),
 "LOC"    VARCHAR2(13),
 "EMPS" "EMP_TAB_TYPE")
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
STORAGE(INITIAL 131072 NEXT 131072
        MINEXTENTS 1 MAXEXTENTS 4096
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
        BUFFER_POOL DEFAULT)
TABLESPACE "USERS"
NESTED TABLE "EMPS"
   STORE AS "EMPS_NT"
   ( (empno NOT NULL, unique (empno), primary key(nested_table_id,empno))
     organization index compress 1 )
   RETURN AS VALUE
/
